### ISSUE TITLE
[bug] core dump, main thread waiting for child thread enable , but part of ctx not use. 

### ISSUE THREAD

**Issue by rryqszq4** [rryqszq4/ngx_php#11]
#0  ngx_strncasecmp (s1=0x0, s2=0x47ceca "unix:", n=5) at src/core/ngx_string.c:598
598	        c1 = (ngx_uint_t) *s1++;
Missing separate debuginfos, use: debuginfo-install cyrus-sasl-lib-2.1.23-13.el6_3.1.x86_64 freetype-2.3.11-15.el6_6.1.x86_64 glibc-2.12-1.132.el6.x86_64 keyutils-libs-1.4-5.el6.x86_64 krb5-libs-1.10.3-37.el6_6.x86_64 libcom_err-1.41.12-21.el6.x86_64 libcurl-7.19.7-40.el6_6.4.x86_64 libgcc-4.4.7-11.el6.x86_64 libidn-1.18-2.el6.x86_64 libselinux-2.0.94-5.8.el6.x86_64 libssh2-1.4.2-1.el6.x86_64 libxml2-2.7.6-21.el6_8.1.x86_64 nspr-4.10.0-1.el6.x86_64 nss-3.15.1-15.el6.x86_64 nss-softokn-freebl-3.14.3-9.el6.x86_64 nss-util-3.15.1-3.el6.x86_64 openldap-2.4.23-32.el6_4.1.x86_64 openssl-1.0.1e-30.el6.11.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) bt
#0  ngx_strncasecmp (s1=0x0, s2=0x47ceca "unix:", n=5) at src/core/ngx_string.c:598
#1  0x000000000040bcb2 in ngx_parse_url (pool=0xbd3af0, u=<value optimized out>) at src/core/ngx_inet.c:531
#2  0x00000000004791c6 in ngx_http_php_socket_tcp_run (r=0xbd3b40)
    at /mnt/hgfs/ngx_php/src/ngx_http_php_socket_tcp.c:56
#3  0x0000000000471eb8 in ngx_http_php_content_thread_inline_handler (r=0xbd3b40)
    at /mnt/hgfs/ngx_php/src/ngx_http_php_handler.c:1106
#4  0x0000000000470622 in ngx_http_php_content_handler (r=<value optimized out>)
    at /mnt/hgfs/ngx_php/src/ngx_http_php_handler.c:236
#5  0x000000000042d51b in ngx_http_core_content_phase (r=0xbd3b40, ph=0x994918)
    at src/http/ngx_http_core_module.c:1417
#6  0x0000000000427e83 in ngx_http_core_run_phases (r=0xbd3b40) at src/http/ngx_http_core_module.c:888
#7  0x0000000000427f93 in ngx_http_handler (r=<value optimized out>) at src/http/ngx_http_core_module.c:871
#8  0x00000000004307a5 in ngx_http_process_request (r=0xbd3b40) at src/http/ngx_http_request.c:1900
#9  0x0000000000432f01 in ngx_http_process_request_headers (rev=<value optimized out>)
    at src/http/ngx_http_request.c:1331
#10 0x000000000043347a in ngx_http_process_request_line (rev=0x7fd0a1b74488) at src/http/ngx_http_request.c:1012
#11 0x0000000000433760 in ngx_http_keepalive_handler (rev=0x7fd0a1b74488) at src/http/ngx_http_request.c:3179
#12 0x000000000041c459 in ngx_event_process_posted (cycle=0x9460c0, posted=0x6ad9c0)
    at src/event/ngx_event_posted.c:40
#13 0x000000000041c27b in ngx_process_events_and_timers (cycle=0x9460c0) at src/event/ngx_event.c:275
#14 0x00000000004221f7 in ngx_single_process_cycle (cycle=0x9460c0) at src/os/unix/ngx_process_cycle.c:315
#15 0x0000000000406245 in main (argc=<value optimized out>, argv=<value optimized out>) at src/core/nginx.c:404

**Comment by rryqszq4** [comment]
fixd
